// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbUU7VNbrVbH1hjp6YwjuvqnBcaBydn6Y',
    appId: '1:1086865769395:web:6a292802309050e49401c6',
    messagingSenderId: '1086865769395',
    projectId: 'metadatalagu-65c26',
    authDomain: 'metadatalagu-65c26.firebaseapp.com',
    databaseURL: 'https://metadatalagu-65c26-default-rtdb.firebaseio.com',
    storageBucket: 'metadatalagu-65c26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxB7rmDoEt7f6jlKCNNEzCyxHGE5TV9U',
    appId: '1:1086865769395:android:6a9b8d69f9fd4a4b9401c6',
    messagingSenderId: '1086865769395',
    projectId: 'metadatalagu-65c26',
    databaseURL: 'https://metadatalagu-65c26-default-rtdb.firebaseio.com',
    storageBucket: 'metadatalagu-65c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkPwiYuMQNFtm2PRRpA-F-VkkJiKWzwLM',
    appId: '1:1086865769395:ios:9108fb3a890d1bf89401c6',
    messagingSenderId: '1086865769395',
    projectId: 'metadatalagu-65c26',
    databaseURL: 'https://metadatalagu-65c26-default-rtdb.firebaseio.com',
    storageBucket: 'metadatalagu-65c26.firebasestorage.app',
    iosBundleId: 'com.example.metadataCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkPwiYuMQNFtm2PRRpA-F-VkkJiKWzwLM',
    appId: '1:1086865769395:ios:9108fb3a890d1bf89401c6',
    messagingSenderId: '1086865769395',
    projectId: 'metadatalagu-65c26',
    databaseURL: 'https://metadatalagu-65c26-default-rtdb.firebaseio.com',
    storageBucket: 'metadatalagu-65c26.firebasestorage.app',
    iosBundleId: 'com.example.metadataCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbUU7VNbrVbH1hjp6YwjuvqnBcaBydn6Y',
    appId: '1:1086865769395:web:203e20e9870d9a529401c6',
    messagingSenderId: '1086865769395',
    projectId: 'metadatalagu-65c26',
    authDomain: 'metadatalagu-65c26.firebaseapp.com',
    databaseURL: 'https://metadatalagu-65c26-default-rtdb.firebaseio.com',
    storageBucket: 'metadatalagu-65c26.firebasestorage.app',
  );
}
